# Generated by Django 5.1.4 on 2025-01-18 08:44

import datetime
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='area_detail',
            field=models.CharField(blank=True, max_length=20, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='page',
            name='code_item_brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='diary.brandmst', to_field='code', verbose_name='品種'),
        ),
        migrations.CreateModel(
            name='HistoricalPage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='ID')),
                ('area_detail', models.CharField(blank=True, max_length=20, verbose_name='地名')),
                ('put_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='入庫日時')),
                ('put_qty', models.IntegerField(verbose_name='入庫数')),
                ('put_wt', models.IntegerField(verbose_name='入庫重量')),
                ('picture', models.TextField(blank=True, max_length=100, null=True, verbose_name='画像')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日時')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('code_area', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diary.areamst', to_field='code', verbose_name='産地')),
                ('code_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diary.itemmst', to_field='code', verbose_name='品目')),
                ('code_item_brand', models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diary.brandmst', to_field='code', verbose_name='品種')),
                ('code_put_human', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diary.humanmst', to_field='code', verbose_name='担当者')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('put_qty_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diary.qtyunitmst', to_field='code', verbose_name='数量単位')),
                ('put_wt_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diary.wtunitmst', to_field='code', verbose_name='重量単位')),
            ],
            options={
                'verbose_name': 'historical page',
                'verbose_name_plural': 'historical pages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
