# Generated by Django 5.1.4 on 2025-02-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_page_area_detail_alter_page_code_item_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmst',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='diary.itemmst', to_field='code', verbose_name='品目コード'),
            preserve_default=False,
        ),
    ]
