# Generated by Django 5.1.4 on 2025-02-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_brandmst_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='部署コード')),
                ('name', models.CharField(max_length=20, verbose_name='部署名称')),
            ],
        ),
        migrations.AddField(
            model_name='historicalpage',
            name='putout_qty',
            field=models.IntegerField(default=1, verbose_name='出庫数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpage',
            name='putout_wt',
            field=models.IntegerField(default=1, verbose_name='出庫重量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='putout_qty',
            field=models.IntegerField(default=1, verbose_name='出庫数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='putout_wt',
            field=models.IntegerField(default=1, verbose_name='出庫重量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areamst',
            name='name',
            field=models.CharField(max_length=20, verbose_name='産地名称'),
        ),
        migrations.AlterField(
            model_name='brandmst',
            name='name',
            field=models.CharField(max_length=50, verbose_name='品種名称'),
        ),
        migrations.AlterField(
            model_name='humanmst',
            name='name',
            field=models.CharField(max_length=20, verbose_name='担当者名称'),
        ),
        migrations.AlterField(
            model_name='itemmst',
            name='name',
            field=models.CharField(max_length=50, verbose_name='品目名称'),
        ),
        migrations.AlterField(
            model_name='qtyunitmst',
            name='name',
            field=models.CharField(max_length=10, verbose_name='数量単位名称'),
        ),
        migrations.AlterField(
            model_name='wtunitmst',
            name='name',
            field=models.CharField(max_length=10, verbose_name='重量単位名称'),
        ),
    ]
