# Generated by Django 5.1.4 on 2025-01-13 06:49

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='産地コード')),
                ('name', models.CharField(max_length=100, verbose_name='産地名称')),
            ],
        ),
        migrations.CreateModel(
            name='BrandMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='品種コード')),
                ('name', models.CharField(max_length=100, verbose_name='品種名称')),
            ],
        ),
        migrations.CreateModel(
            name='HumanMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='担当者コード')),
                ('name', models.CharField(max_length=100, verbose_name='担当者名称')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='品目コード')),
                ('name', models.CharField(max_length=100, verbose_name='品目名称')),
            ],
        ),
        migrations.CreateModel(
            name='QtyUnitMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='数量単位コード')),
                ('name', models.CharField(max_length=100, verbose_name='数量単位名称')),
            ],
        ),
        migrations.CreateModel(
            name='WtUnitMst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='重量単位コード')),
                ('name', models.CharField(max_length=100, verbose_name='重量単位名称')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_detail', models.CharField(max_length=20, verbose_name='地名')),
                ('put_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='入庫日時')),
                ('put_qty', models.IntegerField(verbose_name='入庫数')),
                ('put_wt', models.IntegerField(verbose_name='入庫重量')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='diary/picture/', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.areamst', to_field='code', verbose_name='産地')),
                ('code_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.itemmst', to_field='code', verbose_name='品目')),
                ('code_item_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.brandmst', to_field='code', verbose_name='品種')),
                ('code_put_human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.humanmst', to_field='code', verbose_name='担当者')),
                ('put_qty_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.qtyunitmst', to_field='code', verbose_name='数量単位')),
                ('put_wt_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.wtunitmst', to_field='code', verbose_name='重量単位')),
            ],
        ),
    ]
