# Generated by Django 5.1.4 on 2025-02-24 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_sectionmst_historicalpage_putout_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpage',
            name='putout_section',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diary.sectionmst', to_field='code', verbose_name='出庫先部署'),
        ),
        migrations.AddField(
            model_name='page',
            name='putout_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='diary.sectionmst', to_field='code', verbose_name='出庫先部署'),
            preserve_default=False,
        ),
    ]
