# Generated by Django 5.1.4 on 2025-02-26 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_historicalpage_putout_section_page_putout_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpage',
            name='putout_qty',
        ),
        migrations.RemoveField(
            model_name='historicalpage',
            name='putout_section',
        ),
        migrations.RemoveField(
            model_name='historicalpage',
            name='putout_wt',
        ),
        migrations.RemoveField(
            model_name='page',
            name='putout_qty',
        ),
        migrations.RemoveField(
            model_name='page',
            name='putout_section',
        ),
        migrations.RemoveField(
            model_name='page',
            name='putout_wt',
        ),
        migrations.CreateModel(
            name='PagePutOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('putout_date', models.DateTimeField(auto_now_add=True, verbose_name='出庫日時')),
                ('old_put_qty', models.IntegerField(verbose_name='以前の在庫数')),
                ('putout_qty', models.IntegerField(verbose_name='出庫数')),
                ('old_put_wt', models.IntegerField(verbose_name='以前の在庫重量')),
                ('putout_wt', models.IntegerField(verbose_name='出庫重量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code_putout_human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.humanmst', to_field='code', verbose_name='出庫担当者')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.page')),
                ('putout_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.sectionmst', to_field='code', verbose_name='出庫部署')),
            ],
        ),
    ]
